<?php
/**
 * Created by PhpStorm.
 * User: InkoHX
 * Date: 2018/08/21
 * Time: 23:28
 */

namespace InkoHX;


use pocketmine\event\Listener;
use pocketmine\event\server\DataPacketReceiveEvent;
use pocketmine\network\mcpe\protocol\LoginPacket;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\MainLogger;

class getDevice extends PluginBase implements Listener
{
    const START_MESSAGE = "
    
    §b            __  ___           _        
    §b  ___ ____ / /_/ _ \___ _  __(_)______ 
    §b / _ `/ -_) __/ // / -_) |/ / / __/ -_)
    §b \_, /\__/\__/____/\__/|___/_/\__/\__/ 
    §b/___/                                  
    
    §7          Developer: §eInkoHX
    
    ";

    const OS = [
        "Unknown",
        "Android",
        "iOS",
        "OSX",
        "FireOS",
        "GearVR",
        "HoloLens",
        "Windows10",
        "Windows",
        "Dedicated",
        "Orbis",
        "NX"
    ];

    const PLUGIN_NAME = "§b[§7getDevice§b] §7";

    public function onEnable(): void
    {
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
        MainLogger::getLogger()->info(self::START_MESSAGE);
    }

    public function onDisable(): void
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

    public function onDataPacketReceive(DataPacketReceiveEvent $event): void
    {
        $packet = $event->getPacket();
        if ($packet instanceof LoginPacket) {
            MainLogger::getLogger()->info(self::PLUGIN_NAME . $packet->username . "は§b " . $packet->clientData['DeviceModel'] . " (" . self::OS[$packet->clientData['DeviceOS']] . ") §7を利用しています。");
        }
    }
}